<a href="https://colab.research.google.com/github/BreakoutMentors/Data-Science-and-Machine-Learning/blob/cavlin-numpy-lesson-enhancements/basics/Basics_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

> Note: Always open in Colab for the best learning experience.

# What is NumPy?

[NumPy](https://numpy.org/) is a Python package for scientific computing! What that means is that this package is used to do math with arrays. With numpy, you can create arrays because Python does not have built-in arrays. Python does have lists, but if you remember your data structures, lists take up unnecessary space in memory while arrays sizes are static. Also, NumPy does calculations super fast! That is a plus whenever we do math.


# These are the Basics!

In [2]:
# importing NumPy
import numpy as np

## Intiializing Arrays from lists and tuples

For context, 2-D arrays can also be expressed as matrices in mathematical terminology.

In [ ]:
# Can convert lists into arrays
list_a = [1, 2, 3, 4]

a = np.array(list_a)
a

array([1, 2, 3, 4])

In [ ]:
# Can convert tuples into arrays
tup_a = (1, 2, 3, 4)

a = np.array(tup_a)
a

array([1, 2, 3, 4])

In [ ]:
# You can also create 2-d arrays using numpy

list_2d = [[1, 2, 3, 4],
           [5, 6, 7, 8]]

array_2d = np.array(list_2d)
array_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## How to view the the dimensions of Arrays

In [ ]:
# You can see the shape of the arrays

print('(r, w) means r rows and w columns')
print('Shape of array_2d:', array_2d.shape)
print('Shape of a:', a.shape)

(r, w) means r rows and w columns
Shape of array_2d: (2, 4)
Shape of a: (4,)


## Indexing elements from arrays

In [ ]:
# You can also select elements from arrays:
print('All arrays are zero-indexed\n')
a = np.array([1, 2, 3, 4, 5])

b = np.array([[1, 2, 3, 4, 5],
             [6, 7, 8, 9, 10]])

print('first element of a:', a[0])
print('All elements of a except the first:', a[1:])
print('All elements of a except the last:', a[:4])
print('All elements between the first and the last:', a[1:-1]) # Equivalent to a[1:4]

print('\nThird element of first row of b:', b[0][3]) # Accesses the 0th row, then the 3rd element of that row
print('\nThird element of first row of b:', b[0, 3]) # Accesses the 0th row and the 3rd column (Equivalent to above)

print('Second row of b:', b[1])

All arrays are zero-indexed

first element of a: 1
All elements of a except the first: [2 3 4 5]
All elements of a except the last: [1 2 3 4]

Third element of first row of b: 4
Second row of b: [ 6  7  8  9 10]


## Element wise mathematical operations of arrays and matrices

In [ ]:
# Mathematical Operations with two arrays of the same size!
# Must be the same size

a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

print('THIS IS REALLY IMPORTANT!')
print('These are all element wise:\n')
print('Adding a+b:', a+b)
print('Subtracting a-b:', a-b) #Pretty cool pattern
print('Dividing b/a:', b/a)
print("Multiplying a*b:", a*b)

THIS IS REALLY IMPORTANT!
These are all element wise:

Adding a+b: [ 7  9 11 13 15]
Subtracting a-b: [-5 -5 -5 -5 -5]
Dividing b/a: [6.         3.5        2.66666667 2.25       2.        ]
Multiplying a*b: [ 6 14 24 36 50]


To do element-wise mathematical operations with matrices, they matrices need to have the same shape.

In [ ]:
matrix_a = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8]])

matrix_b = np.array([[10, 9, 8, 7],
                     [6, 5, 4, 3]])
if matrix_a.shape == matrix_b.shape:
    print('They both have the same shape!')

print('\nThese are all element wise:\n')
print('Adding a+b:\n', matrix_a+matrix_b)
print('Subtracting a-b:\n', matrix_a-matrix_b) #Pretty cool pattern
print('Dividing b/a:\n', matrix_b/matrix_a)
print("Multiplying a*b:\n", matrix_a*matrix_b)

They both have the same shape!

These are all element wise:

Adding a+b:
 [[11 11 11 11]
 [11 11 11 11]]
Subtracting a-b:
 [[-9 -7 -5 -3]
 [-1  1  3  5]]
Dividing b/a:
 [[10.          4.5         2.66666667  1.75      ]
 [ 1.2         0.83333333  0.57142857  0.375     ]]
Multiplying a*b:
 [[10 18 24 28]
 [30 30 28 24]]


Often, NumPy can also perform these operations on arrays with different size.

In [17]:
matrix_a = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8]])

matrix_b = np.array([[1], [2]])

print("Matrix a: ")
print(matrix_a)
print("Matrix b: ")
print(matrix_b, '\n')

if matrix_a.shape != matrix_b.shape:
    print('They don\'t have the same shape!\n')


print('Adding a+b:\n', matrix_a+matrix_b)
print('Subtracting a-b:\n', matrix_a-matrix_b)
print('Dividing b/a:\n', matrix_b/matrix_a)
print("Multiplying a*b:\n", matrix_a*matrix_b)

Matrix a: 
[[1 2 3 4]
 [5 6 7 8]]
Matrix b: 
[[1]
 [2]] 

They don't have the same shape!

Adding a+b:
 [[ 2  3  4  5]
 [ 7  8  9 10]]
Subtracting a-b:
 [[0 1 2 3]
 [3 4 5 6]]
Dividing b/a:
 [[1.         0.5        0.33333333 0.25      ]
 [0.4        0.33333333 0.28571429 0.25      ]]
Multiplying a*b:
 [[ 1  2  3  4]
 [10 12 14 16]]


## Scalar Mathematical Operations with Arrays and matrices

In [ ]:
# Scaler Mathematical Operations which only uses one array

a = np.array([1, 2, 3, 4, 5])

print('Multiplying 2*a:', 2*a)
print('Dividing a/2:', a/2)
print('Adding a+2:', a+2)
print('Subtracting a-2:', a-2)

Multiplying 2*a: [ 2  4  6  8 10]
Dividing a/2: [0.5 1.  1.5 2.  2.5]
Adding a+2: [3 4 5 6 7]
Subtracting a-2: [-1  0  1  2  3]


In [ ]:
# Scaler Mathematical Operations with a matrix

a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

print('Multiplying 2*a:\n', 2*a)
print('Dividing a/2:\n', a/2)
print('Adding a+2:\n', a+2)
print('Subtracting a-2:\n', a-2)

Multiplying 2*a:
 [[ 2  4  6  8]
 [10 12 14 16]]
Dividing a/2:
 [[0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4. ]]
Adding a+2:
 [[ 3  4  5  6]
 [ 7  8  9 10]]
Subtracting a-2:
 [[-1  0  1  2]
 [ 3  4  5  6]]


## Special Linear Algebra Mathematical Operations

Two Linear Algebra mathematical operations will be used frequently in our ML cirriculum:
1. Dot-Product of two arrays
![dot product](http://media5.datahacker.rs/2020/04/Picture27-1024x386.jpg)
2. Matrix Multiplication (PLEASE WATCH GIF)
![Matrix Multiplication](https://www.mathwarehouse.com/algebra/matrix/images/matrix-multiplication/how-to-multiply-2-matrices-demo.gif)

Something to notice is that there is a pattern to matrix multiplication that will help. For matrix multiplication to happen, the number of columns in matrix A is equal to the number of rows in matrix B for A*B.



In [ ]:
# Dot Product
a = np.array([2, 7, 1])
b = np.array([8, 2, 8])

print('Dot product of a and b:', a.dot(b))

Dot product of a and b: 38


In [ ]:
# Matrix Multiplication
matrix_a = np.array([[1, 4, 6]])

matrix_b = np.array([[2, 3],
                     [5, 8],
                     [7, 9]])

print("Matrix A:\n", matrix_a)
print("Matrix B:\n", matrix_b)

print("A * B =", np.matmul(matrix_a, matrix_b))

Matrix A:
 [[1 4 6]]
Matrix B:
 [[2 3]
 [5 8]
 [7 9]]
A * B = [[64 89]]


## Copying Arrays and Matrices

The reason you would do this is to prevent changing an array that is important for you, so having a copy allows you to change it with no worries of impacting the original array or matrix.

In [ ]:
# You can copy arrays

a = np.array([1, 2, 3, 4, 5])
a_copy = a.copy() # This is how you copy
print('a_copy:', a_copy)

a_copy: [1 2 3 4 5]


In [ ]:
# You can copy matrices

a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])
a_copy = a.copy() # This is how you copy
print('a_copy:\n', a_copy)

a_copy:
 [[1 2 3 4]
 [5 6 7 8]]


## Reshaping arrays and matrices

In [ ]:
# Reshaping arrays

# a is a 2d array
a = np.array([[1, 2, 3, 4, 5],
             [6, 7, 8, 9, 10]])
print('a:\n', a)
print('Shape of a:', a.shape)

# You can flatten the array into a 1d array
flat_a = a.reshape(-1)

print('\nFlattening a...')
print('Flat a:', flat_a)
print('Shape of flat_a:', flat_a.shape)

# You can change a 1d array look like a column
col_a = flat_a.reshape(-1, 1)# -1 references to the number of elements in the array

print('\nConverting 1d array flat_a to a column...')
print('col_a:\n', col_a)
print('Shape of col_a:', col_a.shape)# A column has r rows and 1 column

# You can change a 1d array look like a row
row_a = flat_a.reshape(1, -1)

print('\nConverting 1d array flat_a to a row...')
print('row_a:\n', row_a)
print('Shape of row_a:', row_a.shape)# A row has 1 row and w columns

print('-'*50)
print('\nBOTH row_a AND col_a ARE 2-D ARRAYS!!!!!')

a:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Shape of a: (2, 5)

Flattening a...
Flat a: [ 1  2  3  4  5  6  7  8  9 10]
Shape of flat_a: (10,)

Converting 1d array flat_a to a column...
col_a:
 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
Shape of col_a: (10, 1)

Converting 1d array flat_a to a row...
row_a:
 [[ 1  2  3  4  5  6  7  8  9 10]]
Shape of row_a: (1, 10)
--------------------------------------------------

BOTH row_a AND col_a ARE 2-D ARRAYS!!!!!


## Transposing a matrix

A matrix is transposed when we swith the order of its dimensions. For a 2D matrix, this looks like a reflection across the diagonal.

In [24]:
a = np.arange(9).reshape(3,3)
print("Matrix a")
print(a)

print("\n Transposed Matrix")
print(a.T) # See np.transpose for more than 2 axes

Matrix a
[[0 1 2]
 [3 4 5]
 [6 7 8]]

 Transposed Matrix
[[0 3 6]
 [1 4 7]
 [2 5 8]]


# Those are the basics!!

This NumPy tutorial is good enough for what we will be learning with Data Science and Machine Learning. NumPy is a super fundamental tool for Data Science and I hope that we both master this tool together.

# Test out your own numpy arrays below!