<a href="https://colab.research.google.com/github/krmiddlebrook/intro_to_deep_learning/blob/master/basics/Basics_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is NumPy?

[NumPy](https://numpy.org/) is a Python package for scientific computing! What that means is that this package is used to do math with arrays. With numpy, you can create arrays because Python does not have built-in arrays. Python does have lists, but if you remember your data structures, lists take up unnecessary space in memory while arrays sizes are static. Also, NumPy does calculations super fast! That is a plus whenever we do math.


## These are the Basics!

In [ ]:
# importing NumPy
import numpy as np

In [ ]:
# Can convert lists into arrays
list_a = [1, 2, 3, 4]

a = np.array(list_a)
a

array([1, 2, 3, 4])

In [ ]:
# Can convert tuples into arrays
tup_a = (1, 2, 3, 4)

a = np.array(tup_a)
a

array([1, 2, 3, 4])

In [ ]:
# You can also create 2-d arrays using numpy

list_2d = [[1, 2, 3, 4],
           [5, 6, 7, 8]]

array_2d = np.array(list_2d)
array_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# You can see the shape of the arrays

print('(r, w) means r rows and w columns')
print('Shape of array_2d:', array_2d.shape)
print('Shape of a:', a.shape)

(r, w) means r rows and w columns
Shape of array_2d: (2, 4)
Shape of a: (4,)


In [ ]:
# You can also select elements from arrays:
print('All arrays are zero-indexed\n')
a = np.array([1, 2, 3, 4, 5])

b = np.array([[1, 2, 3, 4, 5],
             [6, 7, 8, 9, 10]])

print('first element of a:', a[0])
print('All elements of a except the first:', a[1:])
print('All elements of a except the last:', a[:4])

print('\nThird element of first row of b:', b[0][3])
print('Second row of b:', b[1])

All arrays are zero-indexed

first element of a: 1
All elements of a except the first: [2 3 4 5]
All elements of a except the last: [1 2 3 4]

Third element of first row of b: 4
Second row of b: [ 6  7  8  9 10]


In [ ]:
# Mathematical Operations with two arrays of the same size!
# Must be the same size

a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

print('THIS IS REALLY IMPORTANT!')
print('These are all element wise:\n')
print('Adding a+b:', a+b)
print('Subtracting a-b:', a-b) #Pretty cool pattern
print('Dividing b/a:', b/a)
print("Multiplying a*b:", a*b)

THIS IS REALLY IMPORTANT!
These are all element wise:

Adding a+b: [ 7  9 11 13 15]
Subtracting a-b: [-5 -5 -5 -5 -5]
Dividing b/a: [6.         3.5        2.66666667 2.25       2.        ]
Multiplying a*b: [ 6 14 24 36 50]


In [ ]:
# Scaler Mathematical Operations which only uses one array

a = np.array([1, 2, 3, 4, 5])

print('Multiplying 2*a:', 2*a)
print('Dividing a/2:', a/2)
print('Adding a+2:', a+2)
print('Subtracting a-2:', a-2)

Multiplying 2*a: [ 2  4  6  8 10]
Dividing a/2: [0.5 1.  1.5 2.  2.5]
Adding a+2: [3 4 5 6 7]
Subtracting a-2: [-1  0  1  2  3]


In [ ]:
# You can copy arrays

a = np.array([1, 2, 3, 4, 5])
a_copy = a.copy() # This is how you copy
print('a_copy:', a_copy)

a_copy: [1 2 3 4 5]


In [ ]:
# Reshaping arrays

# a is a 2d array
a = np.array([[1, 2, 3, 4, 5],
             [6, 7, 8, 9, 10]])
print('a:\n', a)
print('Shape of a:', a.shape)

# You can flatten the array into a 1d array
flat_a = a.reshape(-1)

print('\nFlattening a...')
print('Flat a:', flat_a)
print('Shape of flat_a:', flat_a.shape)

# You can change a 1d array look like a column
col_a = flat_a.reshape(-1, 1)# -1 references to the number of elements in the array

print('\nConverting 1d array flat_a to a column...')
print('col_a:\n', col_a)
print('Shape of col_a:', col_a.shape)# A column has r rows and 1 column

# You can change a 1d array look like a row
row_a = flat_a.reshape(1, -1)

print('\nConverting 1d array flat_a to a row...')
print('row_a:\n', row_a)
print('Shape of row_a:', row_a.shape)# A row has 1 row and w columns

print('-'*50)
print('\nBOTH row_a AND col_a ARE 2-D ARRAYS!!!!!')

a:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Shape of a: (2, 5)

Flattening a...
Flat a: [ 1  2  3  4  5  6  7  8  9 10]
Shape of flat_a: (10,)

Converting 1d array flat_a to a column...
col_a:
 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
Shape of col_a: (10, 1)

Converting 1d array flat_a to a row...
row_a:
 [[ 1  2  3  4  5  6  7  8  9 10]]
Shape of row_a: (1, 10)
--------------------------------------------------

BOTH row_a AND col_a ARE 2-D ARRAYS!!!!!


# Those are the basics!!

This NumPy tutorial is good enough for what we will be learning with Data Science and Machine Learning. NumPy is a super fundamental tool for Data Science and I hope that we both master this tool together.

# Test out your own numpy arrays below!